### ISSUE TITLE
Request for new wiki: Pickle

### ISSUE THREAD

**Issue by picklerz** [chainwikinet/wikijs-meta-content#1]
We want to have a place to share info about how our protocol works and your platform looks ideal.

Here's our site: http://pickle.finance/

It has links to our Twitter and Discord if you want to learn more. Or we can discuss on this issue as well.

**Comment by BigBrainBriner** [comment]
@brandoncurtis do you know if ChainWiki will consider this? If not, we will move to other solutions, thanks!

**Comment by brandoncurtis** [comment]
@BigBrainBriner @picklerz Granted!
- https://pickle.chainwiki.dev/
- https://github.com/chainwikinet/wikijs-pickle-content/

Sign up with the Github option and then please let me know who should be added in an administrative role.
